In [3]:
import numpy as np

# 1차원 배열
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
# 2차원 배열
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
# 튜플로 1차원 배열 만들기
tpl = (4, 5, 6)
arr = np.array(tpl)
print(arr)

[4 5 6]


In [8]:
# 튜플로 2차원 배열 만들기
lst = [[1,2,3], [4,5,6]]
arr = np.array(lst)
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
# 형상(shape) 확인하기
arr = np.array([1, 2, 3])  # 1차원 배열
print(arr.shape)

(3,)


In [10]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) # 2차원 배열
print(arr2.shape)

(2, 3)


In [11]:
arr = np.array([1, 2, 3])  # 1차원 배열 생성
print(arr.ndim) # 해당 배열의 차원 확인

1


In [12]:
print(arr.size) # 해당 배열의 칸 수 확인

3


In [14]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2.ndim) # 해당 배열의 차원 확인

2


In [15]:
print(arr2.size) # 해당 배열의 칸 수 확인

6


In [16]:
arr = np.array([1.1, 2.2, 3.3])
print(arr.dtype) # 타입 확인

float64


In [4]:
arr = np.array([1.1, 2.2, 3.3], dtype=int)
print(arr) # int 타입으로 변환

[1 2 3]


In [18]:
print(arr.dtype)

int32


In [19]:
arr = np.array([1, 2, 3, 0], dtype=bool)
print(arr) # boolean 타입으로 변환

[ True  True  True False]
