In [3]:
import numpy as np
np.array([[1, 3, 5], [4, 5, 6]])


array([[1, 3, 5],
       [4, 5, 6]])

In [5]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a.shape

(3, 3)

In [10]:
a = np.array(['a', 'b', 1, 2])
print(a[0:2])
print(a[:])

['a' 'b']
['a' 'b' '1' '2']


In [14]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[1:, :])

[[4 5 6]
 [7 8 9]]


In [17]:
a[1,1] = 9
a

array([[1, 2, 3],
       [4, 9, 6],
       [7, 8, 9]])

In [23]:
n1 = np.array([3, 6, 9])

print(n1)
print(n1 + 5)
print(n1 -3)
print(n1 / 5)
print(n1%5)

[3 6 9]
[ 8 11 14]
[0 3 6]
[0.6 1.2 1.8]
[3 1 4]


In [26]:
n2 = np.array([3, 6, 9])

print(n1.dot(n2))

[ 6 12 18]
126


In [29]:
print(n1[n1>5])

[6 9]
